name: Continuous Delivery
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build (${{ matrix.target }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          # linux/amd64
          - os: ubuntu-latest
            target: x86_64-unknown-linux-musl
          # linux/arm64
          - os: ubuntu-latest
            target: aarch64-unknown-linux-musl
          # linux/arm/v7
          - os: ubuntu-latest
            target: armv7-unknown-linux-musleabihf
          # linux/arm/v6
          - os: ubuntu-latest
            target: arm-unknown-linux-musleabihf
          # MacOS: Intel (TODO: add Apple Silicon once Big Sur is available)
          - os: macos-latest
            target: x86_64-apple-darwin
          # Windows
          - os: windows-latest
            target: x86_64-pc-windows-msvc
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      # With each cache weighing in at ~500MB per target,
      # and this repository maxing out at 5GB of caches,
      # it might make sense not to cache dependencies.
      - name: Cache dependencies
        uses: Swatinem/rust-cache@v1

      - name: Install Rust Cross
        run: cargo install cross

      - name: Run dist
        run: cargo xtask dist ${{ matrix.target }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.target }}
          path: ./target/dist/
          if-no-files-found: error
